site_name: My Docs

theme:
  name: material
  palette:
    primary: teal

plugins:
  - i18n:
      default_language: de
      languages:
        de: Deutsch
        fr: Français
      #nav_translations:
        #de:
          #Topic1: Sujet1
        #fr:
         # Topic2: Sujet2
extra:
  alternate:
    - name: Default (de)
      link: ./
      lang: de
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr

markdown_extensions:
  - admonition
  - toc:
      permalink: false